### ISSUE TITLE
Support for Deezer and Apple Music

### ISSUE THREAD

**Issue by sarcasterXO** [Takiyo0/Kazagumo#11]
I would really love to see the support for Deezer and Apple Music if it's possible. Also, discord.js is releasing `v14` so adding support to it too would be great.

**Comment by Takiyo0** [comment]
Hello, I will try adding Apple and Deezer support for this module soon with some fixes. But, what do you mean making this module support v14? I have a bot with v14 and this module works fine, let me know what is your problem with kazagumo in v14.

**Comment by sarcasternub** [comment]
Sorry, I didn't knew it is compatible with v14 too. I have seen `shoukaku` not working well when v13 was released and kazagumo is based on shoukaku so I thought there might be problems with v14 too. I'll use it v14 and let you know if I get some issues. Good luck man you're doing a great job

**Comment by pasindu20** [comment]
> Hello, I will try adding Apple and Deezer support for this module soon with some fixes. But, what do you mean making this module support v14? I have a bot with v14 and this module works fine, let me know what is your problem with kazagumo in v14.

Thank you making it like erela it easy to recode to this npm
 `Deezer and Apple Music` support waiting to see this on feutre

**Comment by RainyXeon** [comment]
@sarcasterXO I think this plugin will help you
https://www.npmjs.com/package/kazagumo-deezer

**Comment by sarcasterXO** [comment]
> @sarcasterXO I think this plugin will help you https://www.npmjs.com/package/kazagumo-deezer
> 
> For the Apple Music, im trying to get the info song from it but idk how to get that.

tbh I can make it too but ig takiyo was already working on it so i didn't. but let's see once i again start working on my bot's rewrite i may create a plugin for apple music too.

**Comment by Nico-ITA** [comment]
> 

The problem is that when u provide to a search function a deezer link the lavalink server resolve it using yt source instead of getting the native deezer audio . ( I have the https://github.com/TopiSenpai/LavaSrc plugin )

**Comment by RainyXeon** [comment]
@Nico-ITA, @sarcasterXO Now v3 can play native deezer audio and other src using lavalink plugin
