### ISSUE TITLE
Docs parsing is not working well

### ISSUE THREAD

**Issue by Jam-Manbo** [Takiyo0/Kazagumo#25]
[`getLeastUsedNode()`](https://takiyo0.github.io/Kazagumo/classes/Kazagumo.Kazagumo.html#getLeastUsedNode) method is displaying its method name wrong. minor issue but it would be great if it gets fixed xD
https://github.com/Takiyo0/Kazagumo/blob/7814983c4f0ef6a6740cfc906e49ebf98f8ba6bd/src/Kazagumo.ts#L246

**Expected behavior**
it should display as `getLeastUsedNode(): Node` not `get Least Used Node(): Node`

**Screenshots**
![image](https://user-images.githubusercontent.com/77767945/204277965-11f47c34-4015-405d-be9c-3da06007ddc7.png)

**Comment by Jam-Manbo** [comment]
since i dont know well about tsdoc, i am not sure if this is intended or not but maybe not ig.
imma add some more bugged things
- https://takiyo0.github.io/Kazagumo/classes/Kazagumo.Kazagumo.html#KazagumoOptions
- https://takiyo0.github.io/Kazagumo/classes/Managers_KazagumoPlayer.KazagumoPlayer.html#guildId
- https://takiyo0.github.io/Kazagumo/classes/Managers_KazagumoPlayer.KazagumoPlayer.html#textId
- https://takiyo0.github.io/Kazagumo/classes/Managers_KazagumoPlayer.KazagumoPlayer.html#voiceId
- https://takiyo0.github.io/Kazagumo/classes/Managers_Supports_KazagumoTrack.KazagumoTrack.html#isSeekable
- https://takiyo0.github.io/Kazagumo/classes/Managers_Supports_KazagumoTrack.KazagumoTrack.html#isStream
- https://takiyo0.github.io/Kazagumo/classes/Managers_Supports_KazagumoTrack.KazagumoTrack.html#realUri
- https://takiyo0.github.io/Kazagumo/classes/Managers_Supports_KazagumoTrack.KazagumoTrack.html#sourceName
- https://takiyo0.github.io/Kazagumo/classes/Modules_Utils.KazagumoUtils.html#convertKazagumoTrackToTrack

seems like some camelCase names are having problem

**Comment by Takiyo0** [comment]
thanks for reporting the issue! I will review the issue and try to fix it after my final exam ends

**Comment by Takiyo0** [comment]
done, from a long ago I guess
