### ISSUE TITLE
Update shoukaku

### ISSUE THREAD

**Issue by justapieop** [Takiyo0/Kazagumo#36]
**Is your feature request related to a problem? Please describe.**
Since Shoukaku is adopting Lavalink v4 API, which is deprecating support for v3 API, I think you should update the library to use v4 API to prevent any possible disruption in the future

**Describe the solution you'd like**
Use latest shoukaku version and make adjustments to make this library fully compatible with v4 API

**Describe alternatives you've considered**
I haven't tried any alternatives

**Additional context**
No

**Comment by Takiyo0** [comment]
done!
