### ISSUE TITLE
Search engine  problem

### ISSUE THREAD

**Issue by Boyfie** [Takiyo0/Kazagumo#50]
When am trying to play songs using Spotify track link it have 40% chances to fetch wrong track example this track https://open.spotify.com/track/2UKK9UEbKlykbmLVP1zWIQ?si=H7IdgTZtTOCp34Y-Vnpp1A

**Comment by Takiyo0** [comment]
Make sure to update to the latest kazagumo-spotify when this issue is closed. Wait until then
