### ISSUE TITLE
Custom source search problem 

### ISSUE THREAD

**Issue by ghost** [Takiyo0/Kazagumo#65]
Kazagumo custom search sources not works properly when I use a custom source like `search(query, { source: "amsearch:" })` Kazagumo searches with the custom source but instantly switches to searching `ytsearch:`, only happen with custom source.

I tried to console log i got this 
![sss](https://github.com/user-attachments/assets/5857fb10-3235-41f9-a62a-eca420f61c86)

![ss](https://github.com/user-attachments/assets/fd1c1018-2bc0-411c-81ba-2d9b4ccadfbe)

**Comment by idMJA** [comment]
you can try using this
https://takiyo0.github.io/Kazagumo/interfaces/Modules_Interfaces.KazagumoOptions.html#defaultSource

For example:
spsearch:
amsearch:
bcsearch:

and more
